- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
  tasks:
    - name: Provision instance
      ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_ID }}"
        ec2_region: "{{ AWS_REGION }}"
        instance_type: t2.micro
        keypair: SSHKEY
        image: ami-098bb5d92c8886ca1 #RHEL 8
        assign_public_ip: yes
        vpc_subnet_id: subnet-c6d2f39a
        group: default
        wait: true
        exact_count: 1
        count_tag:
          Name: Demo1
        instance_tags:
          Name: Demo1
      register: ec2
    - debug:
        var: ec2

    - name: add host to inventory
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: demogroup
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        ansible_ssh_private_key_file: /home/ansible/SSHKEY.pem
      loop: "{{ ec2.instances }}"

- hosts: demogroup
  gather_facts: no
  remote_user: ec2-user
  tasks:
    - name: wait for SSH
      wait_for_connection:
        delay: 5
        timeout: 90

    - name: Check host status
      ping:
